---
repository: https://github.com/Dong--Jian/bash-it.git
version: master
theme: sexy
aliases:
  - ansible
  - emacs
  - general
  - git
  - tmux
plugins:
  - alias-completion
  - base
  - extract
  - proxy
  - tmux
completions:
  - bash-it
  - system
  - git_flow
customs:
  - local_path.bash
  - hadoop.bash
  - history.bash

user: "{{ ansible_user_id }}"
